objects/Pebble_App__c.object
<CustomObject>
    <description>The application that will show on the Pebble screen.</description>
    <fields>
        <fullName>AppTitle__c</fullName>
        <label>Title</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Pebble App</label>
    <nameField>
        <label>Pebble App Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pebble Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pebble_Post__c.object
<CustomObject>
    <description>The Post of an action request from a Pebble App.</description>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Initiating_Row__c</fullName>
        <description>The row from the Pebble App that generated the Post.</description>
        <inlineHelpText>The row from the Pebble App that generated the Post.</inlineHelpText>
        <label>Initiating Row</label>
        <referenceTo>Pebble_Row__c</referenceTo>
        <relationshipLabel>Pebble Posts</relationshipLabel>
        <relationshipName>Pebble_Posts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pebble_App__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Pebble App that created this Post.  This is primarily used to aid in the reporting.</description>
        <inlineHelpText>The parent Pebble App that created this Post.</inlineHelpText>
        <label>Pebble App</label>
        <referenceTo>Pebble_App__c</referenceTo>
        <relationshipLabel>Pebble Posts</relationshipLabel>
        <relationshipName>Pebble_Posts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Row_Codes__c</fullName>
        <description>This entry should only be created by the Pebble App and not be modified.</description>
        <inlineHelpText>This defines the &apos;Pebble Row Name&apos; that was used when the submission to create the Post was created.</inlineHelpText>
        <label>Row Codes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Short_Code__c</fullName>
        <label>Short Code</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <label>Pebble Post</label>
    <nameField>
        <displayFormat>PP{0000000}</displayFormat>
        <label>Pebble Post Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pebble Posts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Pebble_Row__c.object
<CustomObject>
    <description>The individual lines in the Pebble App</description>
    <fields>
        <fullName>Action__c</fullName>
        <description>Changes to this require modifications to the Pebble Watch C and javascript code.</description>
        <inlineHelpText>Cycle - cycle between the different text lines for this Row
Post - create a record in Pebble Post
Case - create a new Case record (*)
Chatter - post to Chatter (*)
Reload - Reload the app
[*-Special formatting required see AppExchange instructions]</inlineHelpText>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cycle</fullName>
                </value>
                <value>
                    <fullName>Post</fullName>
                </value>
                <value>
                    <fullName>Chatter</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Reload</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Custom_Detail__c</fullName>
        <label>Custom Detail</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Custom_Note__c</fullName>
        <description>Use this area to store record IDs or other variables that will be used in the Apex code to initiate  the action desired.</description>
        <inlineHelpText>Use this area to store record IDs or other variables that will be used in the Apex code to initiate  the action desired.</inlineHelpText>
        <label>Custom Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Pebble_App__c</fullName>
        <label>Pebble App</label>
        <referenceTo>Pebble_App__c</referenceTo>
        <relationshipName>Pebble_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>When there are multiple items to be displayed on a row, this determines the Display Order.  There can never be more than 10 items but providing two digits allows for space between rows for insertion of more items without renumbering.</description>
        <inlineHelpText>The order that the item should be displayed.</inlineHelpText>
        <label>Display Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Row__c</fullName>
        <description>This defines which row on the Pebble screen this information will be displayed.</description>
        <inlineHelpText>This defines which row on the Pebble screen this information will be displayed.</inlineHelpText>
        <label>Row</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Short_Code__c</fullName>
        <inlineHelpText>Used to create a unique code for the Post action to use to initiate actions.  Recommended that the code include a separator if you want to part.  eg (&quot;MN1-&quot; or &quot;MN1,&quot;)</inlineHelpText>
        <label>Short Code</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>Pebble Row</label>
    <nameField>
        <displayFormat>PR{000000}</displayFormat>
        <label>Pebble Row Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pebble Row</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Pebble_Post_Action_Test.cls
@isTest
public class Pebble_Post_Action_Test {

    static testMethod void Pebble_Post_Action() {
        
        
		//Create the APP
        Pebble_App__c pa = new Pebble_App__c();
        pa.Name = 'Test App';
        pa.AppTitle__c = 'App Title';
        insert pa;
 
        system.debug('<<<<<<<<<< Now test the new CHATTER function >>>>>>>>>>>>>>>');
        
        //Now add two rows to the App
        //The first row is for the string to be posted
        Pebble_Row__c pr1 = new Pebble_Row__c();
        pr1.Pebble_App__c = pa.Id;
        pr1.Row__c = 1;
        pr1.Priority__c = 1;
        pr1.Custom_Detail__c = 'IsTest Chatter Post';
        pr1.Custom_Note__c = 'Chat Note';
        insert pr1;
        //Now get the system generated feild 'Name' from the new record
        pr1 = [SELECT Name, Custom_Note__c FROM Pebble_Row__c WHERE Id = :pr1.Id];

        //The second row is for the UUID to attach the pst
        Pebble_Row__c pr2 = new Pebble_Row__c();
        pr2.Pebble_App__c = pa.Id;
        pr2.Row__c = 2;
        pr2.Priority__c = 1;
        //The Custom Note is the UUID of where the post is going to be attached
        //You can use record so make it easy and just attach to the Pebble App record
        pr2.Custom_Note__c = pa.Id;
        insert pr2;
        //Now get the system generated feild 'Name' from the new record
        pr2 = [SELECT Name, Custom_Note__c FROM Pebble_Row__c WHERE Id = :pr2.Id];

        //Now build the Post
        Pebble_Post__c pp = new Pebble_Post__c();
        pp.Pebble_App__c = pa.Id;
        pp.Initiating_Row__c = pr2.Id;
        system.debug('CaseTest-' + pr2.Name + '-' + pr1.Name);
        pp.Row_Codes__c = 'ChatTest-' + pr2.Name + '-' + pr1.Name ;
        pp.Action__c = 'Chatter';

		//This insert will initate the Pebble_Post_Chatter trigger        
        insert pp;

        
        //Now build the Post that will fail to test the TRY/Catch code
        Pebble_Post__c pf = new Pebble_Post__c();
        pf.Pebble_App__c = pa.Id;
        pf.Initiating_Row__c = pr2.Id;
        pf.Action__c = 'Chatter';

		//This insert will initate the Pebble_Post_Chatter trigger        
        insert pf;      
        
        system.debug('<<<<<<<<<< Now test the new CASE function >>>>>>>>>>>>>>>');
		// Verify that the initial state is as expected.
		Integer a = [SELECT Count() FROM Case];
        system.debug('Found ' + a + ' records and expected none.');
		System.assertEquals(0, a);
        //First create a CONTACT for this test
		Contact ct = new Contact();
        ct.firstName = 'Dan';
        ct.lastName = 'Harrison';
        insert ct;
        
        //Now add two rows to the App
        //The first row is for the Priority
        Pebble_Row__c cr1 = new Pebble_Row__c();
        cr1.Pebble_App__c = pa.Id;
        cr1.Row__c = 1;
        cr1.Priority__c = 1;
        cr1.Custom_Note__c = 'Low';
        insert cr1;
        //Now get the system generated feild 'Name' from the new record
        cr1 = [SELECT Name, Custom_Note__c FROM Pebble_Row__c WHERE Id = :cr1.Id];
        
		system.debug('cr1 Name:'+cr1.Name + cr1.Id);

        //The second row is for the Contact
        Pebble_Row__c cr2 = new Pebble_Row__c();
        cr2.Pebble_App__c = pa.Id;
        cr2.Row__c = 2;
        cr2.Priority__c = 1;
		//The contact for the test will be BLANK
        system.debug('DEBUG: Got a Contact ID:'+ ct.Id);
        String id15 = ct.Id;
        id15 = id15.substring(0,15);
		cr2.Custom_Note__c = id15;
        insert cr2;
        //Now get the system generated feild 'Name' from the new record
        cr2 = [SELECT Name, Custom_Note__c FROM Pebble_Row__c WHERE Id = :cr2.Id];

        //The third row is for the Type
        Pebble_Row__c cr3 = new Pebble_Row__c();
        cr3.Pebble_App__c = pa.Id;
        cr3.Row__c = 3;
        cr3.Priority__c = 1;
        cr3.Custom_Note__c = 'Test Type';
        cr3.Custom_Detail__c = 'Test line for subject';
        insert cr3;
        //Now get the system generated feild 'Name' from the new record
        cr3 = [SELECT Name, Custom_Note__c FROM Pebble_Row__c WHERE Id = :cr3.Id];

        //Now build the Post
        Pebble_Post__c pp2 = new Pebble_Post__c();
        pp2.Pebble_App__c = pa.Id;
        pp2.Initiating_Row__c = cr2.Id;
        pp2.Short_Code__c = 'test-aa-bb';
        system.debug('CaseTest-' + cr1.Name + '-' + cr2.Name + '-' + cr3.Name);
        pp2.Row_Codes__c = 'CaseTest-' + cr1.Name + '-' + cr2.Name + '-' + cr3.Name;
        pp2.Action__c = 'Case';

		//This insert will initate the Pebble_Post_Chatter trigger        
        insert pp2;
        a = [SELECT Count() FROM Case];
        system.debug('Found ' + a + ' records and expected one.');

        system.debug('DEBUG: Insert Completed record for Test Class.');

        
        //Now build the Post that will fail to test the TRY/Catch code
        Pebble_Post__c pf2 = new Pebble_Post__c();
        pf2.Pebble_App__c = pa.Id;
        pf2.Initiating_Row__c = cr2.Id;
        pf2.Short_Code__c = 'test-aa-bb';
        system.debug('CaseTest-' + cr1.Name + '-' + cr2.Name + '-' + cr3.Name);
        pf2.Row_Codes__c = 'Fail';
        pf2.Action__c = 'Case';

        insert pf2;
        a = [SELECT Count() FROM Case];  //still only should have one record
		System.assertEquals(1, a);

        system.debug('DEBUG: Insert Incomplete record for Test Class.');
        
    }
}